/* CRIAÇÃO DE TABELAS */


create table usuarios(

    ID_USUARIOS INT PRIMARY KEY NOT NULL auto_increment,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(15) NOT NULL UNIQUE,
    TELEFONE VARCHAR(15) NOT NULL,
    SENHA VARCHAR(6) NOT NULL,
    TIPO VARCHAR(15) NOT NULL,
    SALARIO FLOAT, 
    MOTO_MODELO VARCHAR(20),
    MOTO_ANO INT,
    MOTO_PLACA VARCHAR(8)

);

    create table PECAS(
        ID_PECAS INT PRIMARY KEY  NOT NULL auto_increment,
        NOME VARCHAR(50) NOT NULL,
        VALOR_PECAS FLOAT NOT NULL,
        UNIDADE VARCHAR(10) NOT NULL,
        QUANTIDADE INT NOT NULL,
        VALOR_UNIDADE FLOAT NOT NULL,
        TIPO_ELEMENTO VARCHAR(10) NOT NULL

    );
CREATE TABLE PECAS_USADAS (
    NUM_OS INT NOT NULL,
    ID_PECAS INT NOT NULL,
    FOREIGN KEY (NUM_OS) REFERENCES ORDEM_DE_SERVICOS(ID_OS),
    FOREIGN KEY (ID_PECAS) REFERENCES PECAS(ID_PECAS)
);
 create table Ordem_De_Servicos(
        ID_Os INT PRIMARY KEY NOT NULL auto_increment,
        STATUS VARCHAR(10) NOT NULL,
        ID_FUNCIONARIO int NOT NULL, 
        ID_CLIENTE INT NOT NULL,
        CARGA_HORARIA  FLOAT NOT NULL,
        VALOR_PECAS FLOAT NOT NULL,
        VALOR_HH FLOAT NOT NULL,
        VALOR_TOTAL FLOAT NOT NULL,
        OBSERVACAO VARCHAR(150),
        FOREIGN KEY (ID_FUNCIONARIO) REFERENCES usuarios(ID_USUARIOS),
        FOREIGN KEY (ID_CLIENTE) REFERENCES usuarios(ID_USUARIOS)
);
