
USE SMG;

-- PROCEDURE REMOVER_PECAS

DELIMITER $$

CREATE PROCEDURE REMOVER_PECAS(IN p_ID_PECAS INT)
BEGIN	
    DECLARE v_exists INT DEFAULT 0;

    SELECT COUNT(*) INTO v_exists FROM PECAS_USADAS WHERE ID_PECAS = p_ID_PECAS;

    IF v_exists > 0 THEN
        SELECT 'Peça já utilizada em O.S, não pode ser deletada.' AS mensagem;
    ELSE
        DELETE FROM PECAS WHERE ID_PECAS = p_ID_PECAS;
        SELECT 'Peça removida com sucesso.' AS mensagem;
    END IF;
END$$

DELIMITER ;


-- PROCEDURE ORCAMENTO POR NUM OS

DELIMITER $$

CREATE PROCEDURE ORCAMENTO(IN p_num_os INT)
BEGIN
    SELECT 
        OS.ID_OS AS 'NUM OS',
        USU.NOME AS 'CLIENTE',
        USU.MOTO_MODELO AS 'MODELO DA MOTO',
        USU.MOTO_ANO AS 'ANO',
        USU.MOTO_PLACA AS 'PLACA',
        OS.VALOR_PECAS AS 'VALOR PEÇAS',
        OS.VALOR_HH AS 'VALOR MÃO DE OBRA',
        OS.VALOR_TOTAL AS 'VALOR TOTAL'
    FROM 
        ORDEM_DE_SERVICOS OS
        INNER JOIN USUARIOS USU ON OS.ID_CLIENTE = USU.ID_USUARIOS
    WHERE 
        OS.ID_OS = p_num_os;
END$$

DELIMITER ;


-- PROCEDURE DE ORCAMENTO DELIMITANDO POR USUSARIO
DELIMITER $$

CREATE PROCEDURE ORCAMENTO_porUsuario(IN id_cliente INT)
BEGIN
    SELECT 
        OS.ID_OS AS 'NUM OS',
        USU.NOME AS 'CLIENTE',
        USU.MOTO_MODELO AS 'MODELO DA MOTO',
        USU.MOTO_ANO AS 'ANO',
        USU.MOTO_PLACA AS 'PLACA',
        OS.VALOR_PECAS AS 'VALOR PEÇAS',
        OS.VALOR_HH AS 'VALOR MÃO DE OBRA',
        OS.VALOR_TOTAL AS 'VALOR TOTAL'
    FROM 
        ORDEM_DE_SERVICOS OS
        INNER JOIN USUARIOS USU ON OS.ID_CLIENTE = USU.ID_USUARIOS
    WHERE 
        OS.ID_CLIENTE = id_cliente ;
END$$

DELIMITER ;
-- PROCEDURE VERIF_CADASTRO
DELIMITER $$

CREATE PROCEDURE verif_cadastro(IN p_cpf VARCHAR(15), IN p_senha VARCHAR(6))
BEGIN
    DECLARE v_exists INT DEFAULT 0;

    SELECT COUNT(*) INTO v_exists 
    FROM USUARIOS 
    WHERE CPF = p_cpf AND SENHA = p_senha;

    IF v_exists > 0 THEN
        SELECT * FROM USUARIOS WHERE CPF = p_cpf AND SENHA = p_senha;
    ELSE
        SELECT 'USUÁRIO NÃO ENCONTRADO' AS mensagem;
    END IF;
END$$

DELIMITER ;


-- ==============================
-- VIEW RELATORIO_PECAS

CREATE OR REPLACE VIEW RELATORIO_PECAS AS
SELECT
    TIPO_ELEMENTO AS `TIPOS DE ELEMENTOS`,
    SUM(QUANTIDADE) AS UNIDADES,
    MAX(UNIDADE) AS UNIDADE,
    AVG(VALOR_PECAS) AS `VALOR MÉDIO`
FROM 
    PECAS
GROUP BY 
    TIPO_ELEMENTO;
    
    -- VIEW RELATORIO_CLIENTESrelatorio_pecas
    CREATE OR REPLACE VIEW RELATORIO_FUNCIONARIO AS
SELECT * FROM USUARIOS WHERE TIPO="FUNCIONARIO";

